In [1]:
#Problem 1
import something

ModuleNotFoundError: No module named 'something'

In [2]:
try:
    import something
except ModuleNotFoundError:
    print('Module not found.')

Module not found.


In [3]:
#Problem 2
def div(x, y):
    assert y!=0, 'Can\'t divide.'
    return x / y
print(div(8,4))
div(7,0)

2.0


AssertionError: Can't divide.

In [4]:
#Problem 3
def example_func(my_list: list):
    my_sum = 0
    sum_of_pairs = []
    
    for i in range(len(my_list)):
        try:
            sum_of_pairs.append(my_list[i] + my_list[i+1])
        except Exception:
            print('List index out of range.')
    print('sumOfPairs = ', sum_of_pairs)
    
example_func([8, 9, 41, 15, 82, 8, 2, 15, 67])
# Chgitem, chisht em haskacel xndiry)).???

List index out of range.
sumOfPairs =  [17, 50, 56, 97, 90, 10, 17, 82]


In [5]:
#Problem 4
def UpperContent(Textfile):
    try:
        myfile = open(Textfile, 'r')
        for line in myfile:
            print(line.upper())
        myfile.close()
    except Exception:
        print('File not found.')
UpperContent('Textfile.txt')
UpperContent('Text.txt')

HOW ARE YOU?
File not found.


In [6]:
#Problem 5
import numpy as np
x = np.random.randint(1, 11, (3, 5))
print(x)

[[ 6  2  3  1  8]
 [10  1  7  8  2]
 [ 4  4  1  8  8]]


In [7]:
#Problem 6
x = np.zeros(10, dtype = int)
x[4] = 5
print(x)

[0 0 0 0 5 0 0 0 0 0]


In [8]:
#Problem 7
x = np.arange(3, 15)
print(x)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
#Problem 8
x = np.array([1, 3, 5, 2, 4, 5])
y = x.reshape(3, 2)
z = x.reshape(2, 3)
print(y)
print('\n')
print(z)

[[1 3]
 [5 2]
 [4 5]]


[[1 3 5]
 [2 4 5]]


In [27]:
#Problem 9
def func(array1):
    while array1.mean()>5:
        array1 = array1 / 2
    else:
        print(array1)
        
    
array1 = np.array([5, 32, 4, 13, 2, 51, 11, 8, 7])
func(array1)

[ 1.25  8.    1.    3.25  0.5  12.75  2.75  2.    1.75]


In [24]:
#Problem 10
def func1(array):
    print(array[...,0])
    print(array[...,1])
    print(array[...,2])
    print(array[...,3])
def func2(array):
    print(array[0,...])
    print(array[1,...])
    print(array[2,...])
    print(array[3,...])
    print(array[4,...])

array = np.random.randint(1, 11, (5, 4))
print(array, '\n')
print('COLUMNS: ', '\n')
func1(array)
print('\n', 'ROWS: ', '\n')
func2(array)

[[5 7 7 1]
 [8 2 9 6]
 [8 7 2 8]
 [5 2 5 7]
 [6 1 1 8]] 

COLUMNS:  

[5 8 8 5 6]
[7 2 7 2 1]
[7 9 2 5 1]
[1 6 8 7 8]

 ROWS:  

[5 7 7 1]
[8 2 9 6]
[8 7 2 8]
[5 2 5 7]
[6 1 1 8]
